import { Quiz } from './types';

export const SAMPLE_QUIZZES: Quiz[] = [
  // 1. WORLD CAPITALS
  {
    id: 'quiz-world-capitals',
    title: '🏛️ World Capitals Showdown',
    description: 'Test your knowledge on capital cities across Europe, Asia, the Americas, and Africa!',
    coverImage: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 10,
    questions: [
      {
        id: 'cap-1',
        title: 'What is the capital city of Australia?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'c1-1', text: 'Sydney', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'c1-2', text: 'Melbourne', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'c1-3', text: 'Canberra', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'c1-4', text: 'Brisbane', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'cap-2',
        title: 'What is the national capital of Canada?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'c2-1', text: 'Toronto', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'c2-2', text: 'Ottawa', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'c2-3', text: 'Vancouver', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'c2-4', text: 'Montreal', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'cap-3',
        title: 'Which of the following cities officially serve as capitals of South Africa? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 30,
        points: 1500,
        options: [
          { id: 'c3-1', text: 'Pretoria (Executive)', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'c3-2', text: 'Cape Town (Legislative)', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'c3-3', text: 'Bloemfontein (Judicial)', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'c3-4', text: 'Johannesburg', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'cap-4',
        title: 'What is the capital city of Turkey?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'c4-1', text: 'Istanbul', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'c4-2', text: 'Antalya', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'c4-3', text: 'Izmir', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'c4-4', text: 'Ankara', isCorrect: true, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'cap-5',
        title: 'Which of these cities are national capitals in South America? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'c5-1', text: 'Lima (Peru)', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'c5-2', text: 'Bogotá (Colombia)', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'c5-3', text: 'Montevideo (Uruguay)', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'c5-4', text: 'Rio de Janeiro', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
    ],
  },

  // 2. WORLD FLAGS
  {
    id: 'quiz-world-flags',
    title: '🚩 Flags of the World',
    description: 'Explore the fascinating shapes, colors, stars, and emblems of national banners!',
    coverImage: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 9,
    updatedAt: Date.now() - 86400000 * 9,
    questions: [
      {
        id: 'flag-1',
        title: 'Which country has the ONLY national flag that is not rectangular or square?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'fl1-1', text: 'Bhutan', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'fl1-2', text: 'Nepal', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'fl1-3', text: 'Switzerland', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'fl1-4', text: 'Vatican City', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'flag-2',
        title: 'Which countries have plants or trees featured on their official national flags? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'fl2-1', text: 'Canada (Maple Leaf)', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'fl2-2', text: 'Lebanon (Cedar Tree)', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'fl2-3', text: 'Cyprus (Olive Branches)', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'fl2-4', text: 'Japan', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'flag-3',
        title: 'How many yellow stars are displayed on the national flag of China?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'fl3-1', text: '3 Stars', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'fl3-2', text: '4 Stars', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'fl3-3', text: '5 Stars', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'fl3-4', text: '6 Stars', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'flag-4',
        title: 'Which of the following nations have flags consisting strictly of Red, White, and Blue? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'fl4-1', text: 'United States', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'fl4-2', text: 'France', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'fl4-3', text: 'United Kingdom', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'fl4-4', text: 'Germany', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'flag-5',
        title: 'What iconic emblem is portrayed in the center of the flag of Mexico?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'fl5-1', text: 'A golden sun with a face', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'fl5-2', text: 'A soaring condor', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'fl5-3', text: 'An eagle on a cactus eating a snake', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'fl5-4', text: 'A jaguar leaping over ruins', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
    ],
  },

  // 3. GLOBAL CURRENCIES
  {
    id: 'quiz-global-currencies',
    title: '💰 Global Currencies & Money',
    description: 'Travel through the global economy! Test your knowledge on banknotes, coins, and foreign exchange.',
    coverImage: 'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 8,
    questions: [
      {
        id: 'curr-1',
        title: 'What is the official currency of Japan?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'cu1-1', text: 'Won', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'cu1-2', text: 'Yen', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'cu1-3', text: 'Yuan', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'cu1-4', text: 'Ringgit', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'curr-2',
        title: 'Which of the following European countries officially use the Euro (€)? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'cu2-1', text: 'Germany', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'cu2-2', text: 'Spain', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'cu2-3', text: 'Italy', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'cu2-4', text: 'United Kingdom', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'curr-3',
        title: 'What is the currency of South Africa?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'cu3-1', text: 'Dinar', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'cu3-2', text: 'Shilling', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'cu3-3', text: 'Rand', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'cu3-4', text: 'Pula', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'curr-4',
        title: 'Which of these currency pairings are completely ACCURATE? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'cu4-1', text: 'Thailand: Baht', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'cu4-2', text: 'South Korea: Won', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'cu4-3', text: 'Mexico: Peso', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'cu4-4', text: 'India: Dollar', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'curr-5',
        title: 'What is the official currency of Switzerland?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'cu5-1', text: 'Swiss Euro', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'cu5-2', text: 'Krone', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'cu5-3', text: 'Swiss Franc', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'cu5-4', text: 'Guilder', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
    ],
  },

  // 4. WORLD LANGUAGES
  {
    id: 'quiz-world-languages',
    title: '🗣️ World Languages & Polyglots',
    description: 'Explore dialects, language families, native speakers, and linguistic diversity worldwide!',
    coverImage: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 7,
    questions: [
      {
        id: 'lang-1',
        title: 'Which language currently has the largest number of NATIVE speakers worldwide?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'la1-1', text: 'English', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'la1-2', text: 'Spanish', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'la1-3', text: 'Mandarin Chinese', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'la1-4', text: 'Hindi', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'lang-2',
        title: 'Which of the following are official national languages of Switzerland? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'la2-1', text: 'German', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'la2-2', text: 'French', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'la2-3', text: 'Italian', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'la2-4', text: 'Spanish', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'lang-3',
        title: 'What is the primary official language spoken in Brazil?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'la3-1', text: 'Spanish', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'la3-2', text: 'Portuguese', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'la3-3', text: 'Brazilian Latin', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'la3-4', text: 'French', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'lang-4',
        title: 'Which of these languages belong to the Romance language family (derived from Latin)? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'la4-1', text: 'Spanish', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'la4-2', text: 'Italian', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'la4-3', text: 'Romanian', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'la4-4', text: 'German', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'lang-5',
        title: 'Which country has the highest linguistic diversity in the world, with over 800 languages spoken?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'la5-1', text: 'India', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'la5-2', text: 'Papua New Guinea', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'la5-3', text: 'Nigeria', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'la5-4', text: 'Indonesia', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
    ],
  },

  // 5. ICONIC LANDMARKS
  {
    id: 'quiz-iconic-landmarks',
    title: '🗽 Wonders of the World & Landmarks',
    description: 'From ancient pyramids to modern architectural marvels, can you identify the world’s greatest landmarks?',
    coverImage: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now() - 86400000 * 6,
    questions: [
      {
        id: 'lm-1',
        title: 'In which South American nation is the ancient citadel of Machu Picchu located?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'lm1-1', text: 'Chile', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'lm1-2', text: 'Peru', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'lm1-3', text: 'Bolivia', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'lm1-4', text: 'Ecuador', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'lm-2',
        title: 'Which of the following are officially named among the New 7 Wonders of the World? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'lm2-1', text: 'Colosseum (Rome)', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'lm2-2', text: 'Taj Mahal (India)', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'lm2-3', text: 'Great Wall of China', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'lm2-4', text: 'Eiffel Tower (Paris)', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'lm-3',
        title: 'In which city stands the world’s tallest skyscraper, the Burj Khalifa?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'lm3-1', text: 'Doha', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'lm3-2', text: 'Riyadh', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'lm3-3', text: 'Dubai', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'lm3-4', text: 'Abu Dhabi', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'lm-4',
        title: 'Which of these world-famous historic monuments are located in France? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'lm4-1', text: 'Eiffel Tower', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'lm4-2', text: 'Louvre Museum', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'lm4-3', text: 'Palace of Versailles', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'lm4-4', text: 'Sagrada Família', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'lm-5',
        title: 'In which Middle Eastern country can you visit the ancient rock-carved rose-red city of Petra?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'lm5-1', text: 'Egypt', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'lm5-2', text: 'Jordan', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'lm5-3', text: 'Oman', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'lm5-4', text: 'Israel', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
    ],
  },

  // 6. GLOBAL CUISINE & FOOD
  {
    id: 'quiz-global-cuisine',
    title: '🍜 Global Cuisine & Foodie Trek',
    description: 'Savor culinary traditions from street tacos to Asian dumplings and Italian pasta secrets!',
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 5,
    questions: [
      {
        id: 'food-1',
        title: 'Which country is historically credited with originating the crescent-shaped pastry known as the croissant?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'fd1-1', text: 'France', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'fd1-2', text: 'Austria (Vienna Kipferl)', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'fd1-3', text: 'Switzerland', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'fd1-4', text: 'Belgium', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'food-2',
        title: 'Which of the following ingredients are essential to traditional Italian Pesto alla Genovese? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'fd2-1', text: 'Fresh Basil leaves', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'fd2-2', text: 'Pine nuts (Pinoli)', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'fd2-3', text: 'Parmigiano-Reggiano cheese', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'fd2-4', text: 'Tomato puree', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'food-3',
        title: 'Kimchi, a spicy fermented staple dish, originated in which country?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'fd3-1', text: 'Japan', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'fd3-2', text: 'South Korea', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'fd3-3', text: 'Vietnam', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'fd3-4', text: 'Thailand', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'food-4',
        title: 'Which of the following dishes are authentic traditional Mexican specialties? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'fd4-1', text: 'Enchiladas', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'fd4-2', text: 'Tamales', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'fd4-3', text: 'Mole Poblano', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'fd4-4', text: 'Paella Valenciana', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'food-5',
        title: 'What is the primary fruit that serves as the base for traditional guacamole?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'fd5-1', text: 'Mango', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'fd5-2', text: 'Lime', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'fd5-3', text: 'Avocado', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'fd5-4', text: 'Tomatillo', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
    ],
  },

  // 7. SPACE & ASTRONOMY
  {
    id: 'quiz-space-astronomy',
    title: '🚀 Space & Astronomy Odyssey',
    description: 'Blast off into the cosmos! Test your knowledge on planets, moons, galaxies, and black holes.',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now() - 86400000 * 4,
    questions: [
      {
        id: 'sp-1',
        title: 'Which planet in our Solar System is the hottest on average due to runaway greenhouse effect?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'sp1-1', text: 'Mercury', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'sp1-2', text: 'Venus', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'sp1-3', text: 'Mars', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'sp1-4', text: 'Jupiter', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'sp-2',
        title: 'Which of the following are classified as terrestrial (rocky) planets in our Solar System? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'sp2-1', text: 'Mercury', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'sp2-2', text: 'Venus', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'sp2-3', text: 'Mars', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'sp2-4', text: 'Neptune', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'sp-3',
        title: 'Which planet is famous for having the most prominent and majestic ring system visible from Earth?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'sp3-1', text: 'Uranus', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'sp3-2', text: 'Saturn', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'sp3-3', text: 'Jupiter', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'sp3-4', text: 'Neptune', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'sp-4',
        title: 'Which of the following are Galilean moons that orbit the gas giant Jupiter? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'sp4-1', text: 'Europa (Ice moon)', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'sp4-2', text: 'Ganymede (Largest moon)', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'sp4-3', text: 'Callisto', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'sp4-4', text: 'Titan (Orbits Saturn)', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'sp-5',
        title: 'What is the name of the large spiral galaxy closest to our Milky Way?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'sp5-1', text: 'Sombrero Galaxy', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'sp5-2', text: 'Triangulum Galaxy', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'sp5-3', text: 'Andromeda Galaxy (M31)', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'sp5-4', text: 'Centaurus A', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
    ],
  },

  // 8. SCIENCE & INVENTIONS
  {
    id: 'quiz-science-inventions',
    title: '🔬 Science & Greatest Inventions',
    description: 'Celebrate groundbreaking pioneers, Nobel discoveries, chemical elements, and physics laws!',
    coverImage: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 3,
    questions: [
      {
        id: 'sc-1',
        title: 'Who formulated the groundbreaking theories of Special and General Relativity?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'sc1-1', text: 'Isaac Newton', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'sc1-2', text: 'Albert Einstein', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'sc1-3', text: 'Niels Bohr', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'sc1-4', text: 'Stephen Hawking', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'sc-2',
        title: 'Which of the following chemical elements are classified as Noble Gases? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'sc2-1', text: 'Helium (He)', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'sc2-2', text: 'Neon (Ne)', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'sc2-3', text: 'Argon (Ar)', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'sc2-4', text: 'Oxygen (O)', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'sc-3',
        title: 'What is the hardest known naturally occurring mineral on Earth on the Mohs scale?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'sc3-1', text: 'Quartz', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'sc3-2', text: 'Topaz', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'sc3-3', text: 'Diamond', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'sc3-4', text: 'Corundum', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'sc-4',
        title: 'Which of the following scientists were awarded a prestigious Nobel Prize? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'sc4-1', text: 'Marie Curie (Physics & Chemistry)', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'sc4-2', text: 'Albert Einstein (Physics)', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'sc4-3', text: 'Richard Feynman (Physics)', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'sc4-4', text: 'Thomas Edison', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'sc-5',
        title: 'Which subatomic particle possesses a negative electrical charge?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'sc5-1', text: 'Proton', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'sc5-2', text: 'Neutron', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'sc5-3', text: 'Electron', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'sc5-4', text: 'Positron', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
    ],
  },

  // 9. WILD ANIMALS & NATURE
  {
    id: 'quiz-wild-animals',
    title: '🦁 Wild Kingdom & Animal Marvels',
    description: 'From ocean depths to savannah speeds, discover extraordinary facts about creatures of the wild!',
    coverImage: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
    questions: [
      {
        id: 'an-1',
        title: 'What is the fastest land animal in the world, capable of speeds up to 70 mph (112 km/h)?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'an1-1', text: 'Pronghorn Antelope', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'an1-2', text: 'Cheetah', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'an1-3', text: 'Lion', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'an1-4', text: 'Greyhound', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'an-2',
        title: 'Which of the following animals are native marsupials (carry their young in pouches)? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'an2-1', text: 'Kangaroo', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'an2-2', text: 'Koala', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'an2-3', text: 'Wombat', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'an2-4', text: 'Platypus (Monotreme)', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'an-3',
        title: 'What is the largest living mammal (and largest animal known to ever exist) on planet Earth?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'an3-1', text: 'African Bush Elephant', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'an3-2', text: 'Blue Whale', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'an3-3', text: 'Colossal Squid', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'an3-4', text: 'Sperm Whale', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'an-4',
        title: 'Which of the following birds are naturally flightless? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'an4-1', text: 'Emperor Penguin', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'an4-2', text: 'Ostrich', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'an4-3', text: 'Kiwi', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'an4-4', text: 'Albatross', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'an-5',
        title: 'How many hearts does an octopus have?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'an5-1', text: '1 Heart', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'an5-2', text: '2 Hearts', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'an5-3', text: '3 Hearts', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'an5-4', text: '4 Hearts', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
    ],
  },

  // 10. TECH & WEB INNOVATORS
  {
    id: 'quiz-tech-innovators',
    title: '⚡ Ultimate Tech & Coding Challenge',
    description: 'Test your knowledge on web development, famous algorithms, computing history, and modern frameworks!',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now() - 86400000 * 1,
    questions: [
      {
        id: 'tech-1',
        title: 'Which language was created in just 10 days by Brendan Eich in 1995?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 't1-1', text: 'Python', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 't1-2', text: 'JavaScript', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 't1-3', text: 'Java', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 't1-4', text: 'Ruby', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'tech-2',
        title: 'Which of the following are JavaScript frontend frameworks or libraries? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 30,
        points: 1500,
        options: [
          { id: 't2-1', text: 'React', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 't2-2', text: 'Vue.js', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 't2-3', text: 'Django (Python)', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 't2-4', text: 'Svelte', isCorrect: true, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'tech-3',
        title: 'What does CSS stand for?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 't3-1', text: 'Creative Style Sheets', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 't3-2', text: 'Cascading Style Sheets', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 't3-3', text: 'Computer Style Syntax', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 't3-4', text: 'Colorful Standard Sheets', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'tech-4',
        title: 'Which of these protocols operate over TCP/IP port 443 by default?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 't4-1', text: 'HTTP', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 't4-2', text: 'SSH', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 't4-3', text: 'FTP', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 't4-4', text: 'HTTPS', isCorrect: true, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'tech-5',
        title: 'Which of these are major hyperscale cloud service providers? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 't5-1', text: 'Amazon Web Services (AWS)', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 't5-2', text: 'Google Cloud Platform (GCP)', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 't5-3', text: 'Microsoft Azure', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 't5-4', text: 'Ethernet Core Cloud', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
    ],
  },
];
