import { Quiz } from './types';

export const SAMPLE_QUIZZES: Quiz[] = [
  {
    id: 'quiz-tech-trivia',
    title: '⚡ Ultimate Tech & Coding Challenge',
    description: 'Test your knowledge on web development, famous algorithms, computing history, and modern frameworks!',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 3,
    questions: [
      {
        id: 'q1',
        title: 'Which language was created in just 10 days by Brendan Eich in 1995?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'opt-1-1', text: 'Python', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'opt-1-2', text: 'JavaScript', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'opt-1-3', text: 'Java', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'opt-1-4', text: 'Ruby', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'q2',
        title: 'Which of the following are JavaScript frontend frameworks or libraries? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 30,
        points: 1500,
        options: [
          { id: 'opt-2-1', text: 'React', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'opt-2-2', text: 'Vue.js', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'opt-2-3', text: 'Django', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'opt-2-4', text: 'Svelte', isCorrect: true, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'q3',
        title: 'What does CSS stand for?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'opt-3-1', text: 'Creative Style Sheets', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'opt-3-2', text: 'Cascading Style Sheets', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'opt-3-3', text: 'Computer Style Syntax', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'opt-3-4', text: 'Colorful Standard Sheets', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'q4',
        title: 'Which of these protocols operate over TCP/IP port 443 by default?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'opt-4-1', text: 'HTTP', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'opt-4-2', text: 'SSH', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'opt-4-3', text: 'FTP', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'opt-4-4', text: 'HTTPS', isCorrect: true, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'q5',
        title: 'Which of these are valid cloud service providers? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'opt-5-1', text: 'Amazon Web Services (AWS)', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'opt-5-2', text: 'Google Cloud Platform (GCP)', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'opt-5-3', text: 'Microsoft Azure', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'opt-5-4', text: 'Ethernet Cloud Corporation', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
    ],
  },
  {
    id: 'quiz-world-wonders',
    title: '🌍 Globe Trotters & World Wonders',
    description: 'Travel around the world answering geography, flags, capitals, and natural marvels questions.',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    creatorId: 'official-quizrush',
    creatorName: 'QuizRush Team',
    creatorEmail: 'team@quizrush.app',
    isPublic: true,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
    questions: [
      {
        id: 'qw1',
        title: 'What is the capital city of Australia?',
        type: 'single',
        timeLimit: 20,
        points: 1000,
        options: [
          { id: 'ow1-1', text: 'Sydney', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'ow1-2', text: 'Melbourne', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'ow1-3', text: 'Canberra', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'ow1-4', text: 'Brisbane', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'qw2',
        title: 'Which of the following countries border France? (Pick MULTIPLE)',
        type: 'multiple',
        timeLimit: 25,
        points: 1500,
        options: [
          { id: 'ow2-1', text: 'Spain', isCorrect: true, color: 'red', shape: 'triangle' },
          { id: 'ow2-2', text: 'Germany', isCorrect: true, color: 'blue', shape: 'diamond' },
          { id: 'ow2-3', text: 'Italy', isCorrect: true, color: 'yellow', shape: 'circle' },
          { id: 'ow2-4', text: 'Poland', isCorrect: false, color: 'green', shape: 'square' },
        ],
      },
      {
        id: 'qw3',
        title: 'Which is the largest ocean on Earth by surface area?',
        type: 'single',
        timeLimit: 15,
        points: 1000,
        options: [
          { id: 'ow3-1', text: 'Atlantic Ocean', isCorrect: false, color: 'red', shape: 'triangle' },
          { id: 'ow3-2', text: 'Indian Ocean', isCorrect: false, color: 'blue', shape: 'diamond' },
          { id: 'ow3-3', text: 'Arctic Ocean', isCorrect: false, color: 'yellow', shape: 'circle' },
          { id: 'ow3-4', text: 'Pacific Ocean', isCorrect: true, color: 'green', shape: 'square' },
        ],
      },
    ],
  },
];
